<?php

/**
 * CHANGE THESE VALUES BELOW TO WHATEVER
 * IS RIGHT FOR YOU.
 *
 * THAT MEANS IF YOU ARE RUNNING THIS LOCALLY
 * YOU WILL PROBABLY ONLY HAVE TO CHANGE THE PASSWORD
 * BUT IF THIS IS GOING LIVE REMEMBER TO CHANGE
 * THE VALUES TO WHAT YOUR WEB HOSTING SOLUTION
 * IS SAYING IS GOOD.
 */

define("DB_HOST", "localhost");
define("DB_USER", "root");
define("DB_PW", "asd");
define("DB_NAME", "bildur");